spring.application.name=url-shortner-springboot
spring.datasource.url=jdbc:mysql://localhost:3306/urlshortnerdb
spring.datasource.username=root
spring.datasource.password=hiten@313001
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=8081
#jwt.secret=dd83835f02103b55cabf7a1daaa08cfa7c5f7a8f
jwt.secret=dd83835f02103b55cabf7a1daaa08cfa7c5f7a8f9b7c3d1e6a0b3c5d7f9a1c3e
jwt.expiration=172800000

logging.level.org.springframework.security=DEBUG
logging.level.org.url.shortner=DEBUG
